version: "3.7"

services:
  password-manager-api-gw:
    container_name: password-manager-api-gw
    image: golang:1.18-alpine
    #depends_on:
    #  - password-manager-user-auth
    ports:
      - ${GW_SERVER_PORT}:${GW_SERVER_PORT}
    environment:
      GW_APPLICATION_NAME: ${GW_APPLICATION_NAME}
      GW_SERVER_PORT: ${GW_SERVER_PORT}
      GW_SERVICE_USER_DATA_MANAGER_GRPC_ADDRESS: ${GW_SERVICE_USER_DATA_MANAGER_GRPC_ADDRESS}
      GW_SERVICE_USER_AUTHORIZATION_GRPC_ADDRESS: ${GW_SERVICE_USER_AUTHORIZATION_GRPC_ADDRESS}
      GW_TIMEOUT_HTTP_SHUTDOWN: ${GW_TIMEOUT_HTTP_SHUTDOWN}
    networks:
      - password-manager-network
    volumes:
      - ../api-gw:/app
    working_dir: /app
    command: sh -c "go run cmd/main.go"

networks:
  password-manager-network:
    external:
      name:  password-manager-network
    driver: bridge