FROM postgres:14.4

RUN apt-get update && apt-get install net-tools -y && apt-get -y install cron -y
RUN apt-get update && apt-get install -y lsb-release && apt-get clean all && apt install wget -y && apt install sudo -y
